name: Fetch and Save Data

on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
  push:
    branches:
      - main

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch and Save Data
        run: |
          curl -sS 'https://vdnh.ru/local/templates/v3_new_header/js/places-s1.js' \
            | sed -E 's/^var places = |;$//g' \
            > backup.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: updating backup.json"
